---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: windowmaker-os
# description will be included in the image's metadata
description: Atomic Fedora using window maker.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
    group-install:
      with-optional: true
      packages:
        - printing

    install:
      packages:
        # windowmaker stack
        - WindowMaker
        - WindowMaker-extra
        - xterm
        - rxvt-unicode
        - xorg-x11-server-Xorg
        - xorg-x11-xinit
        - xorg-x11-xauth
        - xscreensaver
        - xrandr
        - feh
        - sddm

        # system stack
        - NetworkManager-wifi
        - network-manager-applet
        - pavucontrol
        - xdg-user-dirs
        - xdg-utils

        # audio
        - pipewire
        - pipewire-alsa
        - pipewire-pulseaudio
        - wireplumber
        - bluez
        - bluez-tools

        # misc
        - vim
        - starship
        - fish
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages

  # Enable/disable system services expected for this image.
  - type: systemd
    system:
      enabled:
        - bluetooth.service
        - sddm.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
